steps:
  - name: node:$_NODE_VERSION
    entrypoint: npm
    args: ['install']

  - name: node:$_NODE_VERSION
    entrypoint: npm
    args: ['run', 'build:gateway']

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'create-env', 'apps/payment-gateway/dist/.env']
    env:
      - 'NODE_ENV=${_NODE_ENV}'
      - 'CORS_ORIGINS=${_ADMIN_URL}'
      - 'LEMONSQUEEZY_TEST_MODE=false'
    secretEnv:
      [
        'JWT_SECRET',
        'WEBHOOK_SECRET_ENCRYPTION_KEY',
        'DATABASE_URL',
        'REDIS_URL',
        'LEMONSQUEEZY_API_KEY',
        'LEMONSQUEEZY_STORE_ID',
        'LEMONSQUEEZY_WEBHOOK_SECRET',
        'LEMONSQUEEZY_VARIANT_ID',
        'XENDIT_SECRET_KEY',
        'XENDIT_WEBHOOK_TOKEN',
        'ADMIN_USER_EMAIL',
        'ADMIN_USER_PASSWORD',
      ]

  - name: 'gcr.io/cloud-builders/gcloud'
    id: COPY-APP-YAML
    entrypoint: bash
    args:
      - '-e'
      - '-c'
      - |
        cp apps/payment-gateway/app.yaml apps/payment-gateway/dist/app.yaml

  - id: npm-install
    name: node:$_NODE_VERSION
    entrypoint: npm
    args: ['install']
    dir: 'apps/payment-gateway/dist'

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'app.yaml', '--no-cache']
    dir: 'apps/payment-gateway/dist'

  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud app versions list --format="value(version.id)" --sort-by="~version.createTime" --service="gateway" | tail -n +40 | xargs -r gcloud app versions delete --quiet

timeout: 1800s
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _NODE_VERSION: '22'
  _NODE_ENV: production
  _ADMIN_URL: https://admin-dot-${PROJECT_ID}.as.r.appspot.com
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/JWT_SECRET/versions/latest
      env: 'JWT_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/WEBHOOK_SECRET_ENCRYPTION_KEY/versions/latest
      env: 'WEBHOOK_SECRET_ENCRYPTION_KEY'
    - versionName: projects/$PROJECT_ID/secrets/DATABASE_URL/versions/latest
      env: 'DATABASE_URL'
    - versionName: projects/$PROJECT_ID/secrets/REDIS_URL/versions/latest
      env: 'REDIS_URL'
    - versionName: projects/$PROJECT_ID/secrets/LEMONSQUEEZY_API_KEY/versions/latest
      env: 'LEMONSQUEEZY_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/LEMONSQUEEZY_STORE_ID/versions/latest
      env: 'LEMONSQUEEZY_STORE_ID'
    - versionName: projects/$PROJECT_ID/secrets/LEMONSQUEEZY_WEBHOOK_SECRET/versions/latest
      env: 'LEMONSQUEEZY_WEBHOOK_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/LEMONSQUEEZY_VARIANT_ID/versions/latest
      env: 'LEMONSQUEEZY_VARIANT_ID'
    - versionName: projects/$PROJECT_ID/secrets/XENDIT_SECRET_KEY/versions/latest
      env: 'XENDIT_SECRET_KEY'
    - versionName: projects/$PROJECT_ID/secrets/XENDIT_WEBHOOK_TOKEN/versions/latest
      env: 'XENDIT_WEBHOOK_TOKEN'
    - versionName: projects/$PROJECT_ID/secrets/ADMIN_USER_EMAIL/versions/latest
      env: 'ADMIN_USER_EMAIL'
    - versionName: projects/$PROJECT_ID/secrets/ADMIN_USER_PASSWORD/versions/latest
      env: 'ADMIN_USER_PASSWORD'
