runtime: nodejs22
service: worker
entrypoint: node main.js

instance_class: F1

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_instances: 0
  max_instances: 2

inbound_services:
  - warmup

env_variables:
  NODE_ENV: 'development'

handlers:
  - url: /_ah/warmup
    script: auto

  - url: /robots.txt
    static_files: robots.txt
    upload: robots.txt

  - url: /.*
    secure: always
    script: auto
